# zmienne środowiskowe są zdefiniowane w pliku .env w katalogu głownym projektu
services:
  baza:
    image:
      postgres:latest
    container_name: baza-postgres
    networks:
      - backend
    volumes:
#      - path_data=var/lib/postgresql/data
#      - path_cfg:etc/postgresql.conf
      - path_hba:/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
  pgadmin:
    image:
      dpage/pgadmin4:latest
    container_name: pgadmin4
    networks:
      - backend
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
networks:
  backend:
volumes:
    path_hba:




