
###
GET http://localhost:8080


<> 2025-09-01T094424.404.json
<> 2025-09-01T085207.404.html
<> 2025-09-01T074635.404.json
<> 2025-09-01T074611.200.txt
<> 2025-09-01T074521.200.txt

###
GET http://localhost:8080/bye

<> 2025-09-01T094419.200.txt


###
POST http://localhost:8080/post-test

<> 2025-09-01T081236.403.json
<> 2025-09-01T075540.403.json

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Jan",
  "lastname": "Kowalski",
  "email": "jan.kowalski@domain.com",
  "password": "password",
  "role": "ADMIN",
  "mfaEnabled": true
}

###
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "jan.kowalski@domain.com",
  "password": "password"
}

<> 2025-09-02T084743.403.json

###
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "bob",
  "lastname": "onkel",
  "email": "bob.onkel@domain.com",
  "password": "password",
  "role": "ADMIN",
  "mfaEnabled": false
}

<> 2025-09-02T084944.403.json

###
POST http://localhost:8080/api/v1/auth/register