Działania na użytkownikach:

###  Rejestracja nowego użytkownika
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "bob",
  "lastname": "onkel",
  "email": "bober.onkel@domain.com",
  "password": "password",
  "role": "ADMIN",
  "mfaEnabled": false
}

###  Rejestracja nowego użytkownika
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "firstname": "Janusz",
  "lastname": "Kowalewski",
  "email": "janusz.kowalewski@domain.com",
  "password": "password",
  "role": "ADMIN",
  "mfaEnabled": false
}

### Sprawdzenie, czy działa autentykacja użytkownika
POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "jan.kowalski@domain.com",
  "password": "password"
}

### Odświeżenie tokena użytkownika
POST http://localhost:8080/api/v1/auth/refresh-token
Content-Type: application/x-www-form-urlencoded

### Weryfikacja użytkownika tokenem
POST http://localhost:8080/api/v1/auth/verify
Content-Type: application/json

{
  "email": "jan.kowalski@domain.com",
  "code": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYW4ua293YWxza2lAZG9tYWluLmNvbSIsImlhdCI6MTc1Njk2MzMyMywiZXhwIjoxNzU3NTY4MTIzfQ.MQCDfuq58QvLKdSmdjACixvg5QHjuGvbBAV1o12d6KY"
}

### Działania administratora

###
GET http://localhost:8080/api/v1/admin